import { LangSelect } from "../../client/lang-select";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: any;
}) {
  return (
    <html lang={params.lang}>
      <body>
        <LangSelect default={params.lang} />
        <h1>原神 TODO LIST</h1>
        {children}
      </body>
    </html>
  );
}
