export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: any;
}) {
  return (
    <html lang={params.lang}>
      {JSON.stringify(params)}
      Next.js で書き換え中
      <body>{children}</body>
    </html>
  );
}
