import { LangSelect } from "../client/lang-select";
import { DEFAULT_LANG } from "../const/lang";
import { VOCABULARY } from "../data/i18n";

export const metadata = {
  title: VOCABULARY[DEFAULT_LANG].PAGE_TITLE,
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang={DEFAULT_LANG}>
      <body>
        <LangSelect default={DEFAULT_LANG} />
        <h1>{VOCABULARY[DEFAULT_LANG].PAGE_TITLE}</h1>
        {children}
      </body>
    </html>
  );
}
