import { DEFAULT_LANG } from "../const/lang";
import { VOCABULARY } from "../data/i18n";

export const metadata = {
  title: VOCABULARY[DEFAULT_LANG].PAGE_TITLE,
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
